name: Docker deploy

on:
  push:
    branches: main
    tags:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          
      - name: Login to Docker Hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
          
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6 \
            --push . \
            -t jwoglom/ffmpeg-mjpeg-server:latest -t jwoglom/ffmpeg-mjpeg-server:v1.0.0